version: "3"
services:
  # MongoDB services
  mongo:
        image: mongo:5.0.9
        volumes:
                - ~/docker_mongo/mongo/mongo_db:/data/db
                - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
                - ./db_dump:/db_dump
        ports:
              - 27017:27017
        container_name: mongo_container


volumes: 
      mongo_db: {}
